### ISSUE TITLE
server grouping based on environment and custom notification 

### ISSUE THREAD

**Issue by jogendrajangid1** [keymetrics/pm2-plus-tech-questions#104]
Hi Team,

Can we have servers grouping feature? so we can group one type of request handling servers or environments from dashboard only. and custom notification alert as of now getting notification from keymetrics for Exception or down alert with hostname only that's not enough to understand the type of service facing issue for management team if we have custom/editable notification so we can add our business format for internal notifications. if above of feature is already present I like to know more about it. 

Thanks

**Comment by vmarchaud** [comment]
Hello @jogendrajangid1 

We don't currently have these feature, but we are adding your request into our backlog for the future.
Thanks for the suggestion

**Comment by mattehicks** [comment]
It would also be helpful if you added a 'sort' feature as well.   To sort the list of servers by name.
Thanks!

**Comment by vmarchaud** [comment]
For the sort feature see https://github.com/keymetrics/pm2-plus-tech-questions/issues/116
For the alerting one, we added it but in our newer product PM2 Enterprise, see https://pm2.io/doc/en/enterprise/guides/alerting/
