### ISSUE TITLE
unlink and interact stop/delete seems to not work

### ISSUE THREAD

**Issue by camparound-developers** [keymetrics/pm2-plus-tech-questions#202]
Hi,

i wanted to unlink an app from my dashboard with `pm2 link delete`, `pm2 interact delete`, `pm2 unlink`but nothing stops sending data to my dashboard. Server console says it's unlinked and no more interaction config file found.

I'm using pm2 v3.0.3

**Comment by vmarchaud** [comment]
Hello,

Could you please check that no other agent are running with `ps aux | grep Agent` ?
If there are some please kill them
