### ISSUE TITLE
interact delete of non-running application?

### ISSUE THREAD

**Issue by rockrep** [keymetrics/pm2-plus-tech-questions#203]
I managed to link to a non-running application by pointing to a made-up server name, and it shows up in the keymetrics dashboard with the message "no application has been launched" 

Trying to  delete this entry using the "Delete Server" functionality in the dashboard fails with error message "You must use pm2 interact delete" to remove this server.  

Trying "pm2 interact delete _server-name_" fails with "No interaction config file found" because basically there never was a server with this name or an interaction config file.   I'm using a proccess.json file.

So how do I remove this entry from the dashboard?

**Comment by vmarchaud** [comment]
The agent might run somewhere in the background, i would avise to run `pkill Agent` to be sure no other Agent are running.
