### ISSUE TITLE
Alerts in @pm2/io

### ISSUE THREAD

**Issue by jwieren** [keymetrics/pm2-plus-tech-questions#204]
Hi,

As I see in the code, alert functionality that existed in pmx module has been removed in @pm2/io.  Will this ever be re-added? Or alternatively, what is the future strategy for alerts?

PM2 Plus also doesn't seem to have the kind of control / ability to define alerts for particular metrics that used to exist in keymetrics.  Again, I'm interested in knowing what the future holds :)

Thank you,
Jono

**Comment by vmarchaud** [comment]
Hello,

We removed it yes, because we didn't liked the system like it was, too limited and client sided. We are currently re-implementing it for another product (PM2 Enterprise which is simply a better PM2 Plus)
If you want to use it, i would advise to use the old `pmx` package.

**Comment by jwieren** [comment]
Thank you for your reply, and for your quick patch the other week as well. I look forward to seeing what you come up with.
