### ISSUE TITLE
How to tracce on AWS beanstalk

### ISSUE THREAD

**Issue by luisfusim** [keymetrics/pm2-plus-tech-questions#205]
I need to enter as nodejs user on the EC2 Machine to apply reload --trace or why im not geeting the trace and other ASK how to install pm2 profiler this need root or .config on the beanstalk

**Comment by vmarchaud** [comment]
you can enable it by using our apm library : https://pm2.io/doc/en/plus/guide/transaction-tracing/#pm2io
