### ISSUE TITLE
Question: How to throw exceptions correctly

### ISSUE THREAD

**Issue by BuffMcBigHuge** [keymetrics/pm2-plus-tech-questions#208]
We have console.errors scattered through our application, and we'd like a better way to review them, so we're wondering how to display these in the exception/issue panel on PM2 Plus.

Thanks!

**Comment by vmarchaud** [comment]
Hi,

You can use the `notifyError` from the [pm2/io module](https://github.com/keymetrics/pm2-io-apm#report-caught-exceptions). Note that every object you send must be error so they can be correctly parsed by PM2 Plus.
